# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.

# Example IP addressses used in this file:
# 22.22.22.22 - Target staging server's IP address
# 33.33.33.33 - Second worker node in this 2-server setup
# 55.55.55.55 - This IP address is both the VPN server the server used as a bastion / jump host
# 66.66.66.66 - This IP address is the address of a backup server

all:
  vars:
    users:
      # @todo this is where you define which development team members have access to the server.
      # If you need to remove access from someone, do not remove them from this list, but instead set their state: absent
      - name: ddevadat
        ssh_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCr6/DNzYrV+FXzJItkGMhq4lwblVe4noOB6AVdSYmTkifxS2XKt94cWBGNg1PqTi/RNwlTxAWsdyUsOsfi6MyaWYdYOXp9q5yEAwg3eSrOT+qJ4QL0UwA32oZMI8+W3FrTPZ5jaV6vPvykcgk5K7eai/2SzMawiKsJfMjEDTdVsDbClQBNZXtFVimmbPwvK+4dwhlEymTQXzbd/PMMgIOqJlBeCFbug1rIkUgz0PQ6iWLJuVIwh/sZUW4MfXUIxBztuImh90LAtcRNO62Dn4HUx519VgR7lhjIotxdGPggwKeq6WfJ8TOCCBIkJLeyW06AGFsSJVrhrcK+2RiJG1RP ssh-key-2022-02-02
        state: present
        sudoer: true


jump-host:
  hosts:
    opencrvs-countryconfig-bastion-1: # @todo set this to be the hostname of your jump server
      ansible_host: '152.69.203.79'
